export const outsideLands2026Lineup = [
  "Charli xcx",
  "Turnstile",
  "Subtronics",
  "GRiZ",
  "Labrinth",
  "GloRilla",
  "Geese",
  "Clipse",
  "Modest Mouse",
  "Wet Leg",
  "Tinashe",
  "Sierra Ferrell",
  "Odd Mob",
  "OMNOM",
  "Hyperbeam",
  "The Story So Far",
  "¥ØU$UK€ ¥UK1MAT$U",
  "KI/KI",
  "Durand Bernarr",
  "ALLEYCVT",
  "Die Spitz",
  "MPH",
  "Goldie Boutilier",
  "Dylan Brady",
  "Tobiahs",
  "Billie Marten",
  "Faouzia",
  "Bad Nerves",
  "Luke Alessi",
  "Chezile",
  "Sawyer Hill",
  "Nezza",
  "Vertigo",
  "The Strokes",
  "The xx",
  "Djo",
  "Dijon",
  "PinkPantheress",
  "Ethel Cain",
  "Lucy Dacus",
  "Malcolm Todd",
  "Lane 8",
  "Snow Strippers",
  "it's murph",
  "Audrey Hobert",
  "Ben Böhmer",
  "Trixie Mattel",
  "Łaszewo",
  "Sienna Spiro",
  "Sultan + Shepard",
  "Silvana Estrada",
  "Haute & Freddy",
  "Yard Act",
  "Wunderhorse",
  "camoufly",
  "Bandalos Chinos",
  "After",
  "Rio Kosta",
  "Automatic",
  "Racing Mount Pleasant",
  "Bad Juuju",
  "1-800 GIRLS",
  "Red Leather",
  "RYMAN",
  "RÜFÜS DU SOL",
  "Baby Keem",
  "Empire of the Sun",
  "Death Cab for Cutie",
  "Disco Lines",
  "Mariah the Scientist",
  "Not for Radio",
  "Boris Brejcha",
  "The Temper Trap",
  "JADE",
  "kwn",
  "Boys Noize",
  "Destin Conrad",
  "Kingfishr",
  "Balu Brigada",
  "Frost Children",
  "Miss Monique",
  "Carlita",
  "Amble",
  "Momma",
  "Infinity Song",
  "Sports",
  "Marlon Funaki",
  "Night Tapes",
  "X CLUB.",
  "Jim Legxacy",
  "sosocamo",
  "Day We Ran",
  "Cruz Beckham",
  "Britton",
] as const;

export const outsideLands2026Featured = [
  "Charli xcx",
  "RÜFÜS DU SOL",
  "The Strokes",
  "The xx",
  "Baby Keem",
  "Turnstile",
  "Subtronics",
  "GRiZ",
  "Djo",
  "Labrinth",
  "Empire of the Sun",
  "PinkPantheress",
] as const;
